### PR TITLE
Ensure the selector property is present in JSON

### LINKED ISSUE #31: Selector field is not added to Json for Text index creation
in the method `buildAndValidateTextIndex` (https://github.com/cloudant/objective-cloudant/blob/master/ObjectiveCloudant/Operations/CDTCreateQueryIndexOperation.m#L93) the `selector` attribute is not added to the json request.

### PR DESCRIPTION
**Pull request by rhyshort**
## What
Ensure the selector property is emitted in the JSON body to create
query text indexes.

## Reviewers

reviewer @mikerhodes 

## Issues
Fixes #31

### CODE REVIEW

**Comment by mikerhodes** [comment]
I'd like to see a test that previously would fail.

**Comment by rhyshort** [comment]
@mikerhodes test added

**Comment by mikerhodes** [comment]
I suggest squashing all three commits under something like:

```
Fix incorrect selector and fields handing when creating indexes

* selector wasn't put into the POST body at all.
* fields wasn't nested in the index field.
```

**Comment by mikerhodes** [comment]
+1 with the squashing.

**Pull request merged**
